name: flutter_retro
description: Retrospective board for agile workflows.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  cloud_firestore: ^0.9.5+2
  firebase_core: ^0.3.1+1
  firebase_auth: ^0.8.1+4
  firebase_analytics: ^2.0.3
  google_sign_in: ^4.0.1+1
  shared_preferences: 0.5.1+2
  font_awesome_flutter: 8.4.0
  flutter_colorpicker: ^0.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.7.0

flutter_icons:
  android: "app_launcher"
  ios: true
  image_path: "assets/app_launcher.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
     - family: Lato
       fonts:
         - asset: fonts/Lato-Regular.ttf
         - asset: fonts/Lato-Bold.ttf
           weight: 700
     - family: Nunito Sans
       fonts:
         - asset: fonts/NunitoSans-Regular.ttf
         - asset: fonts/NunitoSans-SemiBold.ttf
           weight: 600
         - asset: fonts/NunitoSans-Bold.ttf
           weight: 700